#Runes
#How do the levels of the runes affect them?
#Lightning - increases chance by 1% per level.
#Vampirism - increases chance by 1% per level.
#Bulwark - increases chance by 1% per level.

#TODO: Rune for increasing amount of blocks mined per action.
#TODO: Fix decapitate event.
#TODO: Get Socket_Expander and Tier_Upgrader working properly... again.